---
- name: Copy backend files to server
  become: true
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Extract backend files
  become: true
  shell: |
    cd /home/ubuntu/
    tar -xvf backend.tar.gz

- name: Start pm2
  become: true
  shell: |
    cd /home/ubuntu/backend/
    npm install
    pm2 stop default
    pm2 start npm -- start
