---
- name: Copy Backend Artifacts
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    mode: 0400

- name: Install npm packages
  npm:
    path: /home/ubuntu

- name: Prepare packages
  become: true
  shell: |
    tar -xvzf artifact.tar.gz
    npm run build

- name: Start pm2
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env