---
- name: Extract artifact.tar.gz
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: no
    mode: 0755

- name: Check and install npm
  become: true
  command: npm install

- name: Install npm packages
  become: true
  npm:
    path: /home/ubuntu

- name: Start pm2
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start
